# Generated by Django 3.2.6 on 2021-08-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача(-у)', 'verbose_name_plural': 'Задачи'},
        ),
    ]
